CORE-ROU:
  hostname: 172.16.32.135
  groups:
    - iosxe
  data:
    interfaces:
        - name: ethernet 1/0
          vlan: routed
          ip:   10.139.3.2
          mask: 255.255.255.0
          desc: FROM CORESW TO FAS
        - name: ethernet 0/0
          vlan: routed
          ip:   10.139.4.2
          mask: 255.255.255.0
          desc: TO MAR FROM CORESW
        - name: ethernet 0/1
          vlan: routed
          ip:   10.139.5.2
          mask: 255.255.255.0
          desc: TO HOSPITAL FROM CORESW
    ospf:
<<<<<<< HEAD
      ospf_rid: 5.5.5.5
=======
      ospf_rid: 3.3.3.3
>>>>>>> f5929bdad8590f35d83156edf450e0bbea41a6d5
      ospf_process: "1"
      ospf_networks:
        - ip: 10.139.2.0
          wildcard: 0.0.0.255
          area: "0"
        - ip: 10.139.3.0
          wildcard: 0.0.0.255
          area: "0"
        - ip: 10.139.4.0
          wildcard: 0.0.0.255
          area: "0"
        - ip: 10.139.5.0
          wildcard: 0.0.0.255
          area: "0"
